//! Renders extracted fields into a Rust source file for the types crate.

use crate::parse::Field;

pub(crate) fn types_file(fields: &[Field], clippy_tag: &str) -> String {
    let mut output = String::new();

    output
        .push_str("// Auto-generated by aqc-clippy-toml-parser-generator. Do not edit manually.\n");
    output.push_str(&format!(
        "// Source: rust-lang/rust-clippy tag {clippy_tag}\n"
    ));
    output.push_str(
        "// Regenerate with: cargo run -p aqc-clippy-toml-parser-generator --bin generate\n\n",
    );
    output.push_str("#![allow(\n");
    output.push_str("    clippy::derive_partial_eq_without_eq,\n");
    output.push_str("    clippy::type_complexity,\n");
    output.push_str("    clippy::struct_excessive_bools,\n");
    output.push_str("    clippy::too_many_lines,\n");
    output.push_str("    clippy::str_to_string,\n");
    output.push_str("    clippy::missing_docs_in_private_items,\n");
    output.push_str("    reason = \"generated file mirrors upstream Clippy config surface 1:1; lints that fight the mirror are suppressed here, not on the consumer side\"\n");
    output.push_str(")]\n\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");
    output.push_str(helper_types());

    output.push_str("// Type aliases for Clippy-specific types\n");
    output.push_str("pub type Msrv = Option<String>;\n");
    output.push_str("pub type MacroMatcher = (String, char);\n");
    output.push_str("pub type Rename = (String, String);\n");
    output.push_str("pub type DisallowedPathWithoutReplacement = DisallowedPath;\n\n");

    output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    output.push_str("#[serde(rename_all = \"kebab-case\")]\n");
    output.push_str("pub struct ClippyToml {\n");

    for field in fields {
        if !field.doc.is_empty() {
            output.push_str(&format!("    /// {}\n", field.doc));
        }
        output.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
    }

    output.push_str("}\n\n");

    output.push_str("impl Default for ClippyToml {\n");
    output.push_str("    fn default() -> Self {\n");
    output.push_str("        Self {\n");

    for field in fields {
        let default_value = map_default_value(&field.rust_type, &field.default);
        output.push_str(&format!("            {}: {},\n", field.name, default_value));
    }

    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn map_default_value(rust_type: &str, default: &str) -> String {
    if rust_type == "Msrv" {
        return "None".to_string();
    }
    if rust_type == "MacroMatcher" || rust_type == "Rename" {
        return "Vec::new()".to_string();
    }
    if rust_type == "SourceItemOrderingModuleItemGroupings" {
        return "SourceItemOrderingModuleItemGroupings(Vec::new())".to_string();
    }
    if rust_type == "SourceItemOrderingTraitAssocItemKinds" {
        return "SourceItemOrderingTraitAssocItemKinds(Vec::new())".to_string();
    }
    if rust_type == "SourceItemOrdering" {
        return "SourceItemOrdering(Vec::new())".to_string();
    }
    if rust_type == "SourceItemOrderingWithinModuleItemGroupings" {
        if default.contains("::None") {
            return "SourceItemOrderingWithinModuleItemGroupings::None".to_string();
        }
        return "SourceItemOrderingWithinModuleItemGroupings::Custom(Vec::new())".to_string();
    }
    if default.contains("DEFAULT_") || default.contains(".iter().map") {
        return "Vec::new()".to_string();
    }
    if default == "<_>::default()" {
        return "Vec::new()".to_string();
    }
    if default.contains("MatchLintBehaviour::") && default.contains("WellKnownTypes") {
        return "MatchLintBehaviour::Always".to_string();
    }
    if default.is_empty() {
        return "Vec::new()".to_string();
    }
    default.to_string()
}

fn helper_types() -> &'static str {
    r#"
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisallowedPath {
    Simple(String),
    Detailed {
        path: String,
        reason: Option<String>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MatchLintBehaviour {
    Always,
    Never,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PubUnderscoreFieldsBehaviour {
    AllPubFields,
    PubliclyExported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InherentImplLintScope {
    Crate,
    Module,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrdering(pub Vec<SourceItemOrderingCategory>);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingCategory {
    Enum,
    Impl,
    Module,
    Struct,
    Trait,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrderingModuleItemGroupings(pub Vec<(String, Vec<SourceItemOrderingModuleItemKind>)>);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingModuleItemKind {
    ExternCrate,
    Mod,
    ForeignMod,
    Use,
    Macro,
    GlobalAsm,
    Static,
    Const,
    TyAlias,
    Enum,
    Struct,
    Union,
    Trait,
    TraitAlias,
    Impl,
    Fn,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrderingTraitAssocItemKinds(pub Vec<SourceItemOrderingTraitAssocItemKind>);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingTraitAssocItemKind {
    Const,
    Fn,
    Type,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SourceItemOrderingWithinModuleItemGroupings {
    All,
    None,
    Custom(Vec<String>),
}

"#
}
