// Auto-generated by aqc-clippy-toml-parser-generator. Do not edit manually.
// Source: rust-lang/rust-clippy tag rust-1.95.0
// Regenerate with: cargo run -p aqc-clippy-toml-parser-generator --bin generate

#![allow(
    clippy::derive_partial_eq_without_eq,
    clippy::type_complexity,
    clippy::struct_excessive_bools,
    clippy::too_many_lines,
    clippy::str_to_string,
    clippy::missing_docs_in_private_items,
    reason = "generated file mirrors upstream Clippy config surface 1:1; lints that fight the mirror are suppressed here, not on the consumer side"
)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisallowedPath {
    Simple(String),
    Detailed {
        path: String,
        reason: Option<String>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MatchLintBehaviour {
    Always,
    Never,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PubUnderscoreFieldsBehaviour {
    AllPubFields,
    PubliclyExported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InherentImplLintScope {
    Crate,
    Module,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrdering(pub Vec<SourceItemOrderingCategory>);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingCategory {
    Enum,
    Impl,
    Module,
    Struct,
    Trait,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrderingModuleItemGroupings(
    pub Vec<(String, Vec<SourceItemOrderingModuleItemKind>)>,
);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingModuleItemKind {
    ExternCrate,
    Mod,
    ForeignMod,
    Use,
    Macro,
    GlobalAsm,
    Static,
    Const,
    TyAlias,
    Enum,
    Struct,
    Union,
    Trait,
    TraitAlias,
    Impl,
    Fn,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceItemOrderingTraitAssocItemKinds(pub Vec<SourceItemOrderingTraitAssocItemKind>);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceItemOrderingTraitAssocItemKind {
    Const,
    Fn,
    Type,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SourceItemOrderingWithinModuleItemGroupings {
    All,
    None,
    Custom(Vec<String>),
}

// Type aliases for Clippy-specific types
pub type Msrv = Option<String>;
pub type MacroMatcher = (String, char);
pub type Rename = (String, String);
pub type DisallowedPathWithoutReplacement = DisallowedPath;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct ClippyToml {
    pub absolute_paths_allowed_crates: Vec<String>,
    pub absolute_paths_max_segments: u64,
    pub accept_comment_above_attributes: bool,
    pub accept_comment_above_statement: bool,
    pub allow_comparison_to_zero: bool,
    pub allow_dbg_in_tests: bool,
    pub allow_exact_repetitions: bool,
    pub allow_expect_in_consts: bool,
    pub allow_expect_in_tests: bool,
    pub allow_indexing_slicing_in_tests: bool,
    pub allow_large_stack_frames_in_tests: bool,
    pub allow_mixed_uninlined_format_args: bool,
    pub allow_one_hash_in_raw_strings: bool,
    pub allow_panic_in_tests: bool,
    pub allow_print_in_tests: bool,
    pub allow_private_module_inception: bool,
    pub allow_renamed_params_for: Vec<String>,
    pub allow_unwrap_in_consts: bool,
    pub allow_unwrap_in_tests: bool,
    pub allow_unwrap_types: Vec<String>,
    pub allow_useless_vec_in_tests: bool,
    pub allowed_dotfiles: Vec<String>,
    pub allowed_duplicate_crates: Vec<String>,
    pub allowed_idents_below_min_chars: Vec<String>,
    pub allowed_prefixes: Vec<String>,
    pub allowed_scripts: Vec<String>,
    pub allowed_wildcard_imports: Vec<String>,
    pub arithmetic_side_effects_allowed: Vec<String>,
    pub arithmetic_side_effects_allowed_binary: Vec<(String, String)>,
    pub arithmetic_side_effects_allowed_unary: Vec<String>,
    pub array_size_threshold: u64,
    pub avoid_breaking_exported_api: bool,
    pub await_holding_invalid_types: Vec<DisallowedPathWithoutReplacement>,
    pub blacklisted_names: Vec<String>,
    pub cargo_ignore_publish: bool,
    pub check_incompatible_msrv_in_tests: bool,
    pub check_inconsistent_struct_field_initializers: bool,
    pub check_private_items: bool,
    pub cognitive_complexity_threshold: u64,
    pub const_literal_digits_threshold: usize,
    pub cyclomatic_complexity_threshold: u64,
    pub disallowed_fields: Vec<DisallowedPath>,
    pub disallowed_macros: Vec<DisallowedPath>,
    pub disallowed_methods: Vec<DisallowedPath>,
    pub disallowed_names: Vec<String>,
    pub disallowed_types: Vec<DisallowedPath>,
    pub doc_valid_idents: Vec<String>,
    pub enable_raw_pointer_heuristic_for_send: bool,
    pub enforce_iter_loop_reborrow: bool,
    pub enforced_import_renames: Vec<Rename>,
    pub enum_variant_name_threshold: u64,
    pub enum_variant_size_threshold: u64,
    pub excessive_nesting_threshold: u64,
    pub future_size_threshold: u64,
    pub ignore_interior_mutability: Vec<String>,
    pub inherent_impl_lint_scope: InherentImplLintScope,
    pub large_error_ignored: Vec<String>,
    pub large_error_threshold: u64,
    pub lint_commented_code: bool,
    pub lint_inconsistent_struct_field_initializers: bool,
    pub literal_representation_threshold: u64,
    pub matches_for_let_else: MatchLintBehaviour,
    pub max_fn_params_bools: u64,
    pub max_include_file_size: u64,
    pub max_struct_bools: u64,
    pub max_suggested_slice_pattern_length: u64,
    pub max_trait_bounds: u64,
    pub min_ident_chars_threshold: u64,
    pub missing_docs_allow_unused: bool,
    pub missing_docs_in_crate_items: bool,
    pub module_item_order_groupings: SourceItemOrderingModuleItemGroupings,
    pub module_items_ordered_within_groupings: SourceItemOrderingWithinModuleItemGroupings,
    pub msrv: Msrv,
    pub pass_by_value_size_limit: u64,
    pub pub_underscore_fields_behavior: PubUnderscoreFieldsBehaviour,
    pub recursive_self_in_type_definitions: bool,
    pub semicolon_inside_block_ignore_singleline: bool,
    pub semicolon_outside_block_ignore_multiline: bool,
    pub single_char_binding_names_threshold: u64,
    pub source_item_ordering: SourceItemOrdering,
    pub stack_size_threshold: u64,
    pub standard_macro_braces: Vec<MacroMatcher>,
    pub struct_field_name_threshold: u64,
    pub suppress_restriction_lint_in_const: bool,
    pub too_large_for_stack: u64,
    pub too_many_arguments_threshold: u64,
    pub too_many_lines_threshold: u64,
    pub trait_assoc_item_kinds_order: SourceItemOrderingTraitAssocItemKinds,
    pub trivial_copy_size_limit: Option<u64>,
    pub type_complexity_threshold: u64,
    pub unnecessary_box_size: u64,
    pub unreadable_literal_lint_fractions: bool,
    pub upper_case_acronyms_aggressive: bool,
    pub vec_box_size_threshold: u64,
    pub verbose_bit_mask_threshold: u64,
    pub warn_on_all_wildcard_imports: bool,
    pub warn_unsafe_macro_metavars_in_private_macros: bool,
}

impl Default for ClippyToml {
    fn default() -> Self {
        Self {
            absolute_paths_allowed_crates: Vec::new(),
            absolute_paths_max_segments: 2,
            accept_comment_above_attributes: true,
            accept_comment_above_statement: true,
            allow_comparison_to_zero: true,
            allow_dbg_in_tests: false,
            allow_exact_repetitions: true,
            allow_expect_in_consts: true,
            allow_expect_in_tests: false,
            allow_indexing_slicing_in_tests: false,
            allow_large_stack_frames_in_tests: true,
            allow_mixed_uninlined_format_args: true,
            allow_one_hash_in_raw_strings: false,
            allow_panic_in_tests: false,
            allow_print_in_tests: false,
            allow_private_module_inception: false,
            allow_renamed_params_for: Vec::new(),
            allow_unwrap_in_consts: true,
            allow_unwrap_in_tests: false,
            allow_unwrap_types: Vec::new(),
            allow_useless_vec_in_tests: false,
            allowed_dotfiles: Vec::default(),
            allowed_duplicate_crates: Vec::new(),
            allowed_idents_below_min_chars: Vec::new(),
            allowed_prefixes: Vec::new(),
            allowed_scripts: vec!["Latin".to_string()],
            allowed_wildcard_imports: Vec::new(),
            arithmetic_side_effects_allowed: Vec::new(),
            arithmetic_side_effects_allowed_binary: Vec::new(),
            arithmetic_side_effects_allowed_unary: Vec::new(),
            array_size_threshold: 16 * 1024,
            avoid_breaking_exported_api: true,
            await_holding_invalid_types: Vec::new(),
            blacklisted_names: Vec::new(),
            cargo_ignore_publish: false,
            check_incompatible_msrv_in_tests: false,
            check_inconsistent_struct_field_initializers: false,
            check_private_items: false,
            cognitive_complexity_threshold: 25,
            const_literal_digits_threshold: 30,
            cyclomatic_complexity_threshold: 25,
            disallowed_fields: Vec::new(),
            disallowed_macros: Vec::new(),
            disallowed_methods: Vec::new(),
            disallowed_names: Vec::new(),
            disallowed_types: Vec::new(),
            doc_valid_idents: Vec::new(),
            enable_raw_pointer_heuristic_for_send: true,
            enforce_iter_loop_reborrow: false,
            enforced_import_renames: Vec::new(),
            enum_variant_name_threshold: 3,
            enum_variant_size_threshold: 200,
            excessive_nesting_threshold: 0,
            future_size_threshold: 16 * 1024,
            ignore_interior_mutability: Vec::from(["bytes::Bytes".into()]),
            inherent_impl_lint_scope: InherentImplLintScope::Crate,
            large_error_ignored: Vec::default(),
            large_error_threshold: 128,
            lint_commented_code: false,
            lint_inconsistent_struct_field_initializers: false,
            literal_representation_threshold: 16384,
            matches_for_let_else: MatchLintBehaviour::Always,
            max_fn_params_bools: 3,
            max_include_file_size: 1_000_000,
            max_struct_bools: 3,
            max_suggested_slice_pattern_length: 3,
            max_trait_bounds: 3,
            min_ident_chars_threshold: 1,
            missing_docs_allow_unused: false,
            missing_docs_in_crate_items: false,
            module_item_order_groupings: SourceItemOrderingModuleItemGroupings(Vec::new()),
            module_items_ordered_within_groupings:
                SourceItemOrderingWithinModuleItemGroupings::Custom(Vec::new()),
            msrv: None,
            pass_by_value_size_limit: 256,
            pub_underscore_fields_behavior: PubUnderscoreFieldsBehaviour::PubliclyExported,
            recursive_self_in_type_definitions: true,
            semicolon_inside_block_ignore_singleline: false,
            semicolon_outside_block_ignore_multiline: false,
            single_char_binding_names_threshold: 4,
            source_item_ordering: SourceItemOrdering(Vec::new()),
            stack_size_threshold: 512_000,
            standard_macro_braces: Vec::new(),
            struct_field_name_threshold: 3,
            suppress_restriction_lint_in_const: false,
            too_large_for_stack: 200,
            too_many_arguments_threshold: 7,
            too_many_lines_threshold: 100,
            trait_assoc_item_kinds_order: SourceItemOrderingTraitAssocItemKinds(Vec::new()),
            trivial_copy_size_limit: None,
            type_complexity_threshold: 250,
            unnecessary_box_size: 128,
            unreadable_literal_lint_fractions: true,
            upper_case_acronyms_aggressive: false,
            vec_box_size_threshold: 4096,
            verbose_bit_mask_threshold: 1,
            warn_on_all_wildcard_imports: false,
            warn_unsafe_macro_metavars_in_private_macros: false,
        }
    }
}
