//! Scalar deny.toml field wiring.

use aqc_file_engine_core::{Finding, ScalarAssertion};
use aqc_toml_engine_core::{apply_scalar_assertion, scalar_field_edit};
use toml_edit::DocumentMut;

use crate::requirement::ResolvedDenyTomlRequirements;

use super::scalar_apply::apply_scalar;

pub(super) fn touch_core_scalar_helpers(findings: &mut Vec<Finding>) {
    let dummy = toml_edit::value(true);
    let _ = scalar_field_edit(
        "core-helper-touch".to_owned(),
        Some(&dummy),
        &ScalarAssertion::Present(String::new()),
        &[],
        findings,
    );
    apply_scalar_assertion(
        &mut DocumentMut::new(),
        "core-helper-touch",
        &ScalarAssertion::Absent(String::new()),
        &[],
        &mut Vec::new(),
    );
}

pub(super) fn apply_scalars(
    doc: &mut DocumentMut,
    requirement: &ResolvedDenyTomlRequirements,
    findings: &mut Vec<Finding>,
) {
    apply_scalar(
        doc,
        &["graph"],
        "exclude-dev",
        "graph.exclude-dev",
        &requirement.graph_exclude_dev,
        findings,
    );
    apply_scalar(
        doc,
        &["graph"],
        "exclude-unpublished",
        "graph.exclude-unpublished",
        &requirement.graph_exclude_unpublished,
        findings,
    );
    apply_scalar(
        doc,
        &["graph"],
        "all-features",
        "graph.all-features",
        &requirement.graph_all_features,
        findings,
    );
    apply_scalar(
        doc,
        &["graph"],
        "no-default-features",
        "graph.no-default-features",
        &requirement.graph_no_default_features,
        findings,
    );
    apply_scalar(
        doc,
        &["output"],
        "feature-depth",
        "output.feature-depth",
        &requirement.output_feature_depth,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "version",
        "advisories.version",
        &requirement.advisories_version,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "db-path",
        "advisories.db-path",
        &requirement.advisories_db_path,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "yanked",
        "advisories.yanked",
        &requirement.advisories_yanked,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "disable-yank-checking",
        "advisories.disable-yank-checking",
        &requirement.advisories_disable_yank_checking,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "unmaintained",
        "advisories.unmaintained",
        &requirement.advisories_unmaintained,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "unsound",
        "advisories.unsound",
        &requirement.advisories_unsound,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "maximum-db-staleness",
        "advisories.maximum-db-staleness",
        &requirement.advisories_maximum_db_staleness,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "git-fetch-with-cli",
        "advisories.git-fetch-with-cli",
        &requirement.advisories_git_fetch_with_cli,
        findings,
    );
    apply_scalar(
        doc,
        &["advisories"],
        "unused-ignored-advisory",
        "advisories.unused-ignored-advisory",
        &requirement.advisories_unused_ignored_advisory,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "version",
        "licenses.version",
        &requirement.licenses_version,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "include-dev",
        "licenses.include-dev",
        &requirement.licenses_include_dev,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "include-build",
        "licenses.include-build",
        &requirement.licenses_include_build,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "confidence-threshold",
        "licenses.confidence-threshold",
        &requirement.licenses_confidence_threshold,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses", "private"],
        "ignore",
        "licenses.private.ignore",
        &requirement.licenses_private_ignore,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "unused-allowed-license",
        "licenses.unused-allowed-license",
        &requirement.licenses_unused_allowed_license,
        findings,
    );
    apply_scalar(
        doc,
        &["licenses"],
        "unused-license-exception",
        "licenses.unused-license-exception",
        &requirement.licenses_unused_license_exception,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "multiple-versions",
        "bans.multiple-versions",
        &requirement.bans_multiple_versions,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "multiple-versions-include-dev",
        "bans.multiple-versions-include-dev",
        &requirement.bans_multiple_versions_include_dev,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "wildcards",
        "bans.wildcards",
        &requirement.bans_wildcards,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "allow-wildcard-paths",
        "bans.allow-wildcard-paths",
        &requirement.bans_allow_wildcard_paths,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "highlight",
        "bans.highlight",
        &requirement.bans_highlight,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "workspace-default-features",
        "bans.workspace-default-features",
        &requirement.bans_workspace_default_features,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "external-default-features",
        "bans.external-default-features",
        &requirement.bans_external_default_features,
        findings,
    );
    apply_scalar(
        doc,
        &["bans"],
        "allow-workspace",
        "bans.allow-workspace",
        &requirement.bans_allow_workspace,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "workspace-dependencies"],
        "duplicates",
        "bans.workspace-dependencies.duplicates",
        &requirement.bans_workspace_dependencies_duplicates,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "workspace-dependencies"],
        "include-path-dependencies",
        "bans.workspace-dependencies.include-path-dependencies",
        &requirement.bans_workspace_dependencies_include_path_dependencies,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "workspace-dependencies"],
        "unused",
        "bans.workspace-dependencies.unused",
        &requirement.bans_workspace_dependencies_unused,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "executables",
        "bans.build.executables",
        &requirement.bans_build_executables,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "interpreted",
        "bans.build.interpreted",
        &requirement.bans_build_interpreted,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "enable-builtin-globs",
        "bans.build.enable-builtin-globs",
        &requirement.bans_build_enable_builtin_globs,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "include-dependencies",
        "bans.build.include-dependencies",
        &requirement.bans_build_include_dependencies,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "include-workspace",
        "bans.build.include-workspace",
        &requirement.bans_build_include_workspace,
        findings,
    );
    apply_scalar(
        doc,
        &["bans", "build"],
        "include-archives",
        "bans.build.include-archives",
        &requirement.bans_build_include_archives,
        findings,
    );
    apply_scalar(
        doc,
        &["sources"],
        "unknown-registry",
        "sources.unknown-registry",
        &requirement.sources_unknown_registry,
        findings,
    );
    apply_scalar(
        doc,
        &["sources"],
        "unknown-git",
        "sources.unknown-git",
        &requirement.sources_unknown_git,
        findings,
    );
    apply_scalar(
        doc,
        &["sources"],
        "required-git-spec",
        "sources.required-git-spec",
        &requirement.sources_required_git_spec,
        findings,
    );
    apply_scalar(
        doc,
        &["sources"],
        "unused-allowed-source",
        "sources.unused-allowed-source",
        &requirement.sources_unused_allowed_source,
        findings,
    );
}
